---
# tasks file for configure_vscode
- name: "Customizing Parrot"
  hosts: localhost
  connection: local
  roles:
    - role: "gantsign.visual-studio-code"
      users:
        - username: "{{ ansible_user_id }}"
          visual_studio_code_extensions:
            - ms-python.python
            - streetsidesoftware.code-spell-checker

